FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
LABEL maintainer="weetok@microsoft.com"
LABEL description="CIFAR-10 Docker Container"


RUN mkdir /code
WORKDIR /code
ADD . /code/
ADD DataSets/CIFAR-10 /DataSets/CIFAR-10

RUN mkdir /app
ADD entry.sh /app/
RUN chmod +x /app/entry.sh

ADD downloaddata.sh /app/
ADD downloaddata_train.sh /app/
RUN chmod +x /app/downloaddata.sh
RUN chmod +x /app/downloaddata_train.sh

RUN apt-get update && apt-get install -y --no-install-recommends \
   vim \
   openmpi-bin \
   python3-dev \
   python3-setuptools \
   libjpeg-dev \
   libpng-dev \
   libtiff-dev \
   libjasper-dev \
   python3-pip && \
   pip3 install --upgrade pip

RUN pip3 install https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp35-cp35m-linux_x86_64.whl 
RUN pip3 install -r /code/requirements.txt

ENTRYPOINT ["/app/entry.sh"]

